#Site
title: "Daniel's Blogs"
author: "Daniel Du "
description: "My personal blog, Creating for upload personal  research, coding related resource." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
name: "Daniel's Blogs"
meta_description: "Daniel Du's Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: /
# google_analytics: 'UA-131933074-1'
disqus: 'danghoangnhan-github-io'
include: ["_pages"]
permalink: /:title/

# Pagination
paginate: 6
paginate_path: /page:num/

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "danghoangnhan.1@gmail.com"
twitter_username: "CallMeMrFern"
github_username: "danghoangnhan"
linkedin_username: "daniel-du-4734081b8"
facebook_username: teddddy.bearrrrr
#flickr_username: username
instagram_username: teddddy.bearrrrr
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss
show_excerpts: false

# Used by simple links page
social-links:
  Resume:        https://danghoangnhan.github.io/resume
  LinkedIn:      https://linkedin.com/in/chadbaldwin
  # StackOverflow: https://stackoverflow.com/users/3474677
  # HackerRank:    https://hackerrank.com/chadwin
  GitHub:        https://github.com/danghoangnhan
  Twitter:       https://twitter.com/chad_baldwin
  Reddit:        https://reddit.com/user/chadbaldwin
  Credly:        https://credly.com/users/chadbaldwin
  PluralSight:   https://app.pluralsight.com/profile/chadbaldwin
  Website:       https://chadbaldwin.net

twitter:
  username: chad_baldwin
  card: summary_large_image
social:
  name: Chad Baldwin
  links:
    - https://twitter.com/chad_baldwin
    - https://linkedin.com/in/chadbaldwin
    - https://github.com/danghoangnhan

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
  - books.md
  - bookmarks.md

# Custom vars
version:          1.1.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

google_analytics:
  - UA-185058308-1 # Old GA Universal Analytics property
  - G-RY6FRPMXHZ # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: danghoangnhan/danghoangnhan.github.io


kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

  
excerpt_separator: <!--more-->