#Site
title: "Daniel's Blogs"
author: "Daniel Du"
description: "My personal blog, Creating for upload personal  research, coding related resource." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
name: "Daniel's Blogs"
meta_description: "Daniel Du's Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: /
# google_analytics: 'UA-131933074-1'
disqus: 'https-danghoangnhan-github-io'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  danghoangnhan:
    name: Daniel Du
    display_name: Daniel Du
    gravatar: 34718a0845f14f39287b2b0178a8a3df
    email: danghoangnhan.1@gmail.com
    web: https://danghoangnhan.github.io
    twitter: https://twitter.com/CallMeMrFern
    description: ""

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "danghoangnhan.1@gmail.com"
twitter_username: "CallMeMrFern"
github_username: "danghoangnhan"
linkedin_username: "daniel-du-4734081b8"
facebook_username: teddddy.bearrrrr
#flickr_username: username
instagram_username: teddddy.bearrrrr
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss
show_excerpts: false





# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
  - books.md
  - bookmarks.md



google_analytics:
  - UA-185058308-1 # Old GA Universal Analytics property
  - G-RY6FRPMXHZ # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 1000

# The github repo that is to be used for looking up comments
comments_repo: danghoangnhan/danghoangnhan.github.io

# Pagination
paginate: 6
paginate_path: /page:num/

# kramdown:
#   syntax_highlighter_opts:
#     disable: true

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages


# Custom vars
version:          1.1.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Dependencies
markdown: kramdown
kramdown:
  math_engine: katex
highlighter:      rouge

excerpt_separator: <!--more-->